### ISSUE TITLE
Why is the .exe file too big?

### ISSUE THREAD

**Issue by UnknownAttackerr** [Blank-c/Blank-Grabber#101]
How am I supposed to let someone open this .exe file when I can't share it anywhere due to the size of it? Genuinely wondering! I tested this .exe file myself and I'm absolutely amazed by the detail of information it can grab. Absolutely 10/10 coding, love this so much.

**Comment by Blank-c** [comment]
First of all, thank you for the complement. I really appreciate that.

Second, Pyinstaller does not compile the program to an executable, what it does is it packs the program and the python interpreter together, thus increasing the file size. I have applied almost all the possible ways to reduce the file size, otherwise the size would be more than 12 mb if the grabber is packed normally. So reducing the size more than this is next to impossible.
