### ISSUE TITLE
The Built.exe is Not Sending Information to The Discord Server

### ISSUE THREAD

**Issue by YaGoatt** [Blank-c/Blank-Grabber#104]
It was working normally until about 2 months ago and I wanted to use it again but it's not working well. I mean it's working I checked my task manager and it was there, it's even running my camera. I disabled my antivirus and downloaded the latest version of Python also tried disabling the VM protection but when I try, it just opens the app and runs my camera (it's working at the background when I try to delete the built it says it working so I ended it from the task manager) but not sending the information to the discord server and yes my webhook and all other stuff we're working I tried almost everything, this is probably one of the most useful and easiest rat so please help.

**Comment by Blank-c** [comment]
Okay, so I guess this is because of the Camera file (Many people have complained that the Camera.exe kept running in the background). So can you try this:
    - Delete the `env` folder (if any)
    - Inside the Data folder, edit the main.py file and set [`CAPTURE_WEBCAM`](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/main.py#L40) to `False` and then please tell the results.

Also check if there is some \`invisible\` or \`????\` named folder in your `%temp%` directory. If its there, what files are inside it?

Also do this to see if there is any error, in the Data folder, edit the `run.bat` file with notepad and in [line 30](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/run.bat#L30) remove the ` --noconsole` (including the space before --) and then build it.

**Remember to delete the `env` folder before doing all this.**

**Comment by YaGoatt** [comment]
Oh, yeah I did them all, took a while to send the information I delete the env folder also I had some invisible folders in %temp% they were all Blank rat result files so I delete them. So it's working now thanks for helping.

**Comment by Blank-c** [comment]
So the camera is the issue, I'll need to do something soon

**Comment by YaGoatt** [comment]
I guess so
