### ISSUE TITLE
backdoor 

### ISSUE THREAD

**Issue by CoolTrepur12345** [Blank-c/Blank-Grabber#173]
pretty sure that this tool uses a backdoor to control your pc. I stupidly tested this on my pc without using a virtual machine and now ever since, I've been spamming people with adverts on my discord and I also have been added to different servers withiut any bot authorization after changing my password multiple times. DO NOT DOWNLOAD THIS

**Comment by Blank-c** [comment]
No it doesn't.
The full source code is in front of you, go check it out.
Its not like you searched for a stealer and found this one, then you used it and stayed happy for the rest of your life.
You must have used other stealers too, so why did you assume you got hacked just because of this?

I'd recommend you to use malwareBytes to scan your whole PC and remove all discord folders (from `localappdata` folder)

**Comment by CoolTrepur12345** [comment]
No, I have not used any other stealers. This is the only one I used. The only open sorce software I have downloaded from the internet since getting my new PC is this.

**Comment by Blank-c** [comment]
Then it may be possible that you got hacked from somewhere else. I can assure you that you are not hacked by this. I'd recommend you to scan your whole system, in case, the malware is still present in your system.

**Comment by CoolTrepur12345** [comment]
Should I use avast for the full scan? Or use the one you recommended?

**Comment by Blank-c** [comment]
Malwarebytes
