### ISSUE TITLE
Anti-VM success rate

### ISSUE THREAD

**Issue by loomian** [Blank-c/Blank-Grabber#208]
what's the anti vm success rate? if i integrate your anti-vm script into my rat will it be less detected than this script or no? I noticed with virustotal the more you scan a file the more it gets detected so I was just curious if it's the method getting detected or the scripts itself.

**Comment by Blank-c** [comment]
Anti VM has nothing to do with virustotal's detection rate (or rather with static analysis). Anti VM only provide protection against behavorial analysis. 

About the success rate, its 115% (15% extra because it sometimes flags normal system as VMs too). The rate decreases if the VM is modified specifically for malware analysis. But you don't have to worry about that. Its very rare that someone will analyze your file is a fully modified VM.
