### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by spinbins** [Blank-c/Blank-Grabber#36]
i was just wondering if there is any tools that can make this so when the victim downloads this, the anti virus doesn't go off right away until they open it and its too late. I have made a program to bind this stub to and if you have any programs or tips that can make it undetectable until they open it that would be freaking awesome

**Comment by Blank-c** [comment]
**I thought about it a while ago and this is what in my mind.**

I thought of aes encrypting the grabber (which makes it fully undetectable) and then make a c++ script to decrypt it and run it on the victim's pc. But the problem is that, most of the people do not have any c++ compiler in their pc. and all the c++ compilers are too big. So I passed it

**Comment by spinbins** [comment]
could i potentially get away with it? remember I made a program and I could make them download a c++ compiler as a "requirement" for the app. Same thing with the file size, I could just pass it off as part of my program.

**Comment by Blank-c** [comment]
The antivirus will block the app in the middle of downloads

**Comment by Blank-c** [comment]
There is no way that the grabber can become FUD. Even if it does, it will now or soon be flagged by antiviruses.

I have updated the code to convert the grabber to a .Net exe to reduce virustotal detections.

**Comment by spinbins** [comment]
is there anyway that i could obfuscate it to make it at least be able to execute before it gets picked up and deleted?

**Comment by Blank-c** [comment]
Probably. Not that I know of...
