### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by zappelig** [Blank-c/Blank-Grabber#75]
Use the Crypter thingy that makes it more undetectet and make it clean the trash files in env/scripts, because it looks like there is a lot of weird files that are created while converting to an exe, but they aren't removed.

Thanks.

**Comment by Blank-c** [comment]
My main focus is on the size reduction of the grabber. But the crypter may increase the size of the grabber. Thats why I have not made it to automatically crypt the final stub. The users building the grabber can crypt it if they want.

**Comment by schwungvoll** [comment]
Thanks! But I've got 3 other suggestions. 

1. Disable the AntiVirus directly after opening the file. (So that's the first thing it would do. That causes that the person's AntiVirus can't delete the file/interrupt the process.) E.g. for windows defender, avira, malwarebytes and many other AntiViruses.

2. Search **especially** for **Discord Cookies** on the person's **browser**. Because there are many dumbasses using the fucking Discord Website instead of the Desktop App. And that's why I make this suggestion. It just annoys me. Please add it, because Discord shows now every token on the Website you've logged in with. 

3. A Fake Error Feature, but not like one shitty ass Fake Error where the person has to click "ok" on it that the Grabber transfers the data to you like Luna Grabber's ass Fake Error does. Add like 20 different Fake Error's (You can choose between them in the builder or it's randomly choosed, maybe search for them on google) and an option where you can put your own Fake Error in if you want.

Adding this would be great, thanks!

**Comment by Blank-c** [comment]
1) It already tries to disable defender using registry.

2) I don't get what you want to say. It already gets discord **token** from browsers.

3) Thought about that (ans tried to implement too) but it will raise detections.

**Comment by schwungvoll** [comment]
Okay thanks but I quite don't understand the token thing, I sent a guy my file after he opened (with AntiVirus enabled) I got everything, except the discord data, such as tokens etc...

**Comment by Blank-c** [comment]
hmm, I think I would have to look into it.

**Comment by schwungvoll** [comment]
Into the file that came up to my webhook?

**Comment by Blank-c** [comment]
No, I mean into the issue

**Comment by schwungvoll** [comment]
Oh hahha

**Comment by schwungvoll** [comment]
Thanks

**Comment by schwungvoll** [comment]
Would the error log.txt help?

**Comment by Blank-c** [comment]
ye, please give if you can
