### ISSUE TITLE
Is the main.py will be the payload at the end?

### ISSUE THREAD

**Issue by gtv12c** [Blank-c/Blank-Grabber#80]

**Comment by Blank-c** [comment]
No you will get an exe

**Comment by bakrodeh** [comment]
same question

**Comment by bakrodeh** [comment]
> once I built the payload it show me this https://gyazo.com/50a22a5efca10a39e8b83bb5087800b7

I think it's a fake stealer

**Comment by Blank-c** [comment]
> once i built the payload it show me this https://gyazo.com/50a22a5efca10a39e8b83bb5087800b7

Did the folder open automatically? After you press the build button, a command prompt will open and will then build the file. You will get a single exe named "Blank Grabber.exe"

**Comment by Blank-c** [comment]
@bakrodeh Don't just go on with assumptions

**Comment by gtv12c** [comment]
to make sure everything going clear 
here is the full video during creating it:
https://streamable.com/wfgr1a

**Comment by Blank-c** [comment]
I Just saw the video and there is a problem with your python installation. To recheck, open cmd in an empty folder and run the command `python -m venv env` and then go to a newly created folder `.../env/Scripts`. Check if there is a file named `activate.bat` (which is not there in your video). Try to reinstall python to see if this issue is fixed or not.

**Comment by bakrodeh** [comment]
> @bakrodeh Don't just go on with assumptions

Okay brother ^_^

**Comment by Blank-c** [comment]
Reopen if issue is still there.
